
name: database-deployment

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build:
    # spin up virtual machine with latest version of ubuntu
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@v2
    # set up python version 3.8 on the ubuntu operating system virtual machine
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    # install any require dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install beautifulsoup4
        pip install pandas
        pip install webdriver-manager
        pip install supabase
        pip install python-decouple
    # run python scripy to pull and transform arcgis data to csv to heroku postgres server
    - name: Build database
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        
      run: |
        python scraping_stocking_calendar.py
        python supabase_connection.py
    - name: Commit and push if it changed
      run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add .
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
